site_name: MkDocs Encrypt Source Plugin
repo_url: https://github.com/six-two/mkdocs-encrypt-source-plugin
repo_name: mkdocs-placeholder-plugin

theme:
  name: material
  # name: mkdocs
  # name: readthedocs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.sections
  - content.code.copy
  - navigation.footer
  # For testing issue 7
  - navigation.instant
plugins:
- placeholder:
    placeholder_extra_js: placeholder-extra.js
- badges
- search
- git-revision-date-localized

nav:
- index.md

markdown_extensions:
  # Message/error/warning boxes
  - admonition
  - pymdownx.details
  # Different formatting options
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # For search exclusion
  - attr_list
  # For mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # for tabs
  - pymdownx.tabbed:
      alternate_style: true

# For MkDocs 1.5 do not warn me about absolute links or `iLINKi`
validation:
  absolute_links: ignore
  unrecognized_links: ignore

watch:
- placeholder-plugin.yaml
